name: PR Bot

on:
  push:

jobs:
  pr:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - run: git log v22.11.09.4..v22.11.09.5 --oneline --format=%s
