name: PR Bot

on:
  push:

jobs:
  pr:
      runs-on: ubuntu-latest
      steps:
        - name: Send custom JSON data to Slack workflow
          id: slack
          uses: slackapi/slack-github-action@v1.23.0
          with:
            # For posting a rich message using Block Kit
            payload: |
              {
                "text": "Deploy <${{ github.event.repository.html_url }}/releases/tag/v22.10.25.1|v22.10.25.1> byl zahájen :crossed_fingers:"
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK  

        - name: Send custom JSON data to Slack workflow
          id: slack
          uses: slackapi/slack-github-action@v1.23.0
          with:
            # For posting a rich message using Block Kit
            payload: |
              {
                "text": "Deploy <${{ github.event.repository.html_url }}/releases/tag/v22.10.25.1|v22.10.25.1> byl úspěšně dokončen :white_check_mark:"
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK  