name: PR Bot

on:
  push:
    branches:
      - pdp-*

jobs:
  pr:
      name: PRs
      runs-on: ubuntu-latest
      steps:
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            labels: |
              Základový PR
