name: PR Bot

on:
  push:

jobs:
  pr:
      name: PRs
      runs-on: [self-hosted, k8s]
      steps:
        - uses: actions/checkout@v2
        - name: Create Pull Request
          run: sleep 1000

