name: Slack Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Slack Notify - changes
        run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          echo $LATEST_TAG
          echo $PREVIOUS_TAG
          echo "$(git log --pretty=format:'%an: %s' --reverse $PREVIOUS_TAG...$LATEST_TAG)" >> git.log
          bash slack.sh ${{ secrets.SLACK_WEBHOOK_URL }}
