name: Slack Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tag names
        id: tag_names
        run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          echo $LATEST_TAG
          echo $PREVIOUS_TAG
          echo "$(git log --pretty=format:'%an: %s' --reverse $PREVIOUS_TAG...$LATEST_TAG)" >> git.log

      - name: View payload
        run: cat git.log
