
name: Release Bot

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == 'true'
    name: Run CI Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ls -la
