name: Slack Notification

on:
  release:


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          releases-only: true
        id: octokit

      - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"
