
name: Release Bot

on:
#  pull_request:
#    types: [closed]
  - push

jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: lastVersion
        uses: pozetroninc/github-action-get-latest-release@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: jakubenglicky
          repo: pokusne-repo
      - name: Echo version
        run: echo ${{ steps.lastVersion.outputs.release }}
#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.keydb.outputs.release }}
#          release_name: ${{github.event.pull_request.title}}
#          body: ${{github.event.pull_request.body}}
#          draft: false
#          prerelease: false