
name: Release Bot

on:
  release:
    types:
      - released
jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      # - name: Previous Tag
      #   run: echo "{tag}={$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)}" >> $PREVIOUS_TAG

      - name: Previous Tag
        run: echo "tag=v22.11.09.8" >> $GITHUB_TAG


      - name: Get Git Log
        id: git_log
        uses: JantHsueh/get-git-log-action@master
        with:
          tag: ${{ env.PREVIOUS_TAG }}

      - run: echo ${{ steps.git_log.outputs.log }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": ":construction_worker: Vydáváme <${{ github.event.repository.html_url }}/releases/tag/v22.10.25.1|v22.10.25.1> :crossed_fingers: \n Změny: \n ${{ steps.git_log.outputs.log }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK