
name: Release Bot

on:
  release:
    types:
      - released
jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - id: lastVersion
        name: Get last tag
        uses: jakubenglicky/github-action-get-latest-release@master
        with:
          owner: jakubenglicky
          repo: pokusne-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.previoustag.outputs.tag }}
      
      - name: Set output variables
        id: vars
        run: |
          changes="$(git log v22.11.09.6..v22.11.09.7 --oneline --format=%s)"
          echo "changes=$changes" >> $GITHUB_OUTPUT

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": ":construction_worker: Vydáváme <${{ github.event.repository.html_url }}/releases/tag/v22.10.25.1|v22.10.25.1> :crossed_fingers: \n Změny: \n ${{ steps.vars.outputs.changes }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK