name: Slack Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Slack Notify - changes
        run: bash slack.sh ${{ secrets.SLACK_WEBHOOK_URL }}
