name: Slack Notification

on:
  release:


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          releases-only: true
        id: octokit

      - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      - run: echo ${{ steps.previoustag.outputs.tag }}