name: Print Git log between tags

on:
  push:
    tags:
      - "v*"

jobs:
  print-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag names
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --abbrev=0)
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))

      - name: Print log
        run: |
          git log $PREVIOUS_TAG..$LATEST_TAG --pretty=format:'%h %s - %an'
