name: Print Git log between tags

on:
  push:
    tags:
      - "v*"

jobs:
  print-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Git Log
        id: git_log
        uses: JantHsueh/get-git-log-action@master
   