name: Slack Notification

on:
  push:
    tags:
      - "v*"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag names
        run: |
          echo $(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo $(git describe --abbrev=0 --tags `git rev-list --tags --skip=0 --max-count=1`)

 