name: Slack Notification

on:
  release:


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: octokit  # The step ID to refer to later.

      - run: echo "Octokit is at version ${{ steps.octokit.outputs.tag }}"
