
name: Release Bot

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: lastVersion
        name: Get last tag
        uses: jakubenglicky/github-action-get-latest-release@master
        with:
          owner: jakubenglicky
          repo: pokusne-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: jakubenglicky/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr_number: ${{github.event.pull_request.number}}
          author: ${{github.event.pull_request.user.login}}
          tag_name: ${{ steps.lastVersion.outputs.release }}
          release_name: ${{github.event.pull_request.title}}
          body: ${{github.event.pull_request.body}}
          draft: false
          prerelease: false
      - name: Done Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: "S6: Hotovo"
      - name: Comment with PR link
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            https://github.com/peckadesign/pdproject5/releases/tag/${{ steps.lastVersion.outputs.release }}